/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/
#include <stdint.h>
#ifndef __USB_DEVICE_INTERFACE_0_CIC_VCOM_H__
#define __USB_DEVICE_INTERFACE_0_CIC_VCOM_H__

/*******************************************************************************
 * Definitions
 ******************************************************************************/
extern uint8_t buf[20];
extern uint16_t bufSize;
extern uint8_t cmdReady;
/*!
 * @brief Interface task function.
 */
void USB_DeviceInterface0CicVcomTask(void);
void USB_CommandParse(void);

#endif /* __USB_DEVICE_INTERFACE_0_CIC_VCOM_H__ */
